name = "genesis"
main = "src/index.ts"
compatibility_date = "2024-06-08"


[[d1_databases]]
binding = "DB"
database_name = "genesis"
database_id = "b75ebb55-7fe5-4503-a81c-640daf2dbf78"

[vars]
SALT_TOKEN = ""
