name = "genesis"
main = "ser/server.php"
compatibility_date = "2024-06-08"


[[d1_databases]]
binding = "DB"
database_name = "registro"
database_id = "a0411c02-07eb-4c79-a0a8-b10e7c4ec6e4"

[vars]
SALT_TOKEN = ""


