name = "genesis"
main = "src/index.ts"
compatibility_date = "2024-06-08"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "genesis"
database_id = "dcd69d53-1064-404b-a88c-601f4eec4402"
